language: generic
sudo : required
services : 
  - docker

before_install : 
  - docker build -t leolo0626/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leolo0626/docker-react npm run test

deploy :
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-travis-ci-2"
  env: "DockerReactTravisCi2-env"
  bucket_name : "elasticbeanstalk-us-east-2-752120535986"
  bucket_path : "docker-react-travis-ci-2"
  on : 
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_ACCESS_SECRET"

